//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Core.Repository;
using System;

namespace Core.EntityFramework
{
    using System.Collections.Generic;

    public partial class Portfolio : IEntity
    {
        public Portfolio()
        {
            this.Portfolio_Security = new HashSet<Portfolio_Security>();
        }

        public System.Guid PortfolioId { get; set; }
        public System.Guid UserId { get; set; }

        public virtual ICollection<Portfolio_Security> Portfolio_Security { get; set; }
        public virtual User User { get; set; }

        Guid IEntity.Id
        {
            get { return PortfolioId; }
            set { PortfolioId = value; }
        }
    }
}
