//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlgoTrader.Core.EntityFramework
{
    public partial class Portfolio_Security
    {
        public System.Guid Id { get; set; }
        public System.Guid PortfolioId { get; set; }
        public System.Guid SecurityId { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        public virtual Security Security { get; set; }
    }
}
