//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;

namespace AlgoTrader.Core.EntityFramework
{
    public partial class User
    {
        public User()
        {
            this.Portfolios = new HashSet<Portfolio>();
        }
    
        public System.Guid UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<Portfolio> Portfolios { get; set; }
    }
}
