//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.ORM.EntityFramework
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class AlgorithmicTradingEntities : DbContext
    {
        public AlgorithmicTradingEntities()
            : base("name=AlgorithmicTradingEntities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<Portfolio_Security> Portfolio_Security { get; set; }
        public virtual DbSet<Security> Securities { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
